### ISSUE TITLE
Unable to load critter pages

### ISSUE THREAD

**Issue by wirekitty** [Dimillian/ACHNBrowserUI#328] opened 2020-10-10 04:38 UTC
I am attempting to access the critter pages to update the newest critters I have donated. The spinning wheel appears and the pages never load no matter what critter family I select. I have let it spin for over 30 minutes. I have reloaded app. I have deleted app and redownloaded. Nothing is working to make the critter lists load. 
![1C36877C-A841-4349-AEB6-1234E679C113](https://user-images.githubusercontent.com/72640943/95645834-7e8e0a00-0a88-11eb-8cdd-73c17f0683fc.png)

**Comment by TheVaan** [comment] 2020-10-10 07:04
Thank you for your ticket. It seems to be a duplicate of #321 that already got fixed. The update will be rolled out soon.

**Closed** 2020-10-10 07:04 UTC
