### ISSUE TITLE
fish/bug/sea creature menu keeps loading

### ISSUE THREAD

**Issue by jludorf** [Dimillian/ACHNBrowserUI#330] opened 2020-10-21 19:54 UTC
When you collect every fish/ insect/ sea creature you can in a month the app keeps on loading the screen. It doesn’t crash but also doesn’t display any additional information anymore either.

You don’t even need to catch all of them. Emptying the list of the ongoing month seems to be enough. 

Happens on both my iPhone and iPad Running iOS and iPadOS 14.

**Comment by TheVaan** [comment] 2020-10-21 20:20
Which version of AC Helper is running on your devices?

**Comment by renaudjenny** [comment] 2020-10-21 20:27
Looks a duplicate of #323 to me. It has been fixed recently and the fix has just been publish today.
Please tell us if you can replicate after updating to 2.0.3.
Thanks :).

**Comment by renaudjenny** [comment] 2020-10-21 20:28
Actually a duplicate of #321 😂.

**Comment by jludorf** [comment] 2020-10-21 22:39
> Looks a duplicate of #323 to me. It has been fixed recently and the fix has just been publish today.
> Please tell us if you can replicate after updating to 2.0.3.
> Thanks :).

I just checked and the bug still is present in the most recent version.

Also sorry for not noticing when creating a duplicate report. I really just made this account to report this bug and have zero experience with GitHub.

**Comment by renaudjenny** [comment] 2020-10-22 07:29
@jludorf no problems, actually my bad, I just checked the last version an indeed, the problem still here, I will check later why today.
And don't worry about the duplicate report, that happens all the time on GitHub 😂.
By the way: Welcome to GitHub, and moreover, thank you for this report, knowing that you created an account especially for AC Helper encourages us to continue developing a better application ❤️.
Even it's a duplicate, it's always awesome to have people reporting problems 🙂.

**Closed** 2020-10-23 07:28 UTC
Labels: bug
